### PR TITLE
Change Oscoin event title and details

### PR DESCRIPTION
**Pull request by onurakpolat**
Now that we've defined the specifics of our event a few things changed. It would be great to update on the website as well.

New title: `Radicle - The programming language behind the Oscoin network`

New desc:

```
Users, individually or collectively, should be empowered to shape the technology they use. Software developers are particularly skilled to do that, and yet the most popular code hosting platforms give them little to no ability to enact changes.

In this talk, we present radicle, the language used by the open source coin platform to give developers full control over their code hosting, collaboration, and project governance. Radicle has some unique characteristics - most notably self-amendment, or evaluation-redefinition - that are interesting in their own right. But more importantly, it makes it easy for individuals or groups to collectively determine how they interact with one another, and with their code.

After an overview of radicle, we will look at examples, such as custom formats and behaviors for issues, access rights, and voting. We will also see how radicle can be used not just as a way of defining the semantics of chains, but as as way of interacting *with* them (via scripting or a REPL).
```

Additionally I propose to change the slug accordingly.

### CODE REVIEW

**Comment by onurakpolat** [comment]
@cesalazar 

Oh one more thing, could we add another event/party?

Title: Tunez and BBQ with Oscoin

Desc: Oscoin throws a party after their main  event with fine music and BBQ.

Date: Friday, 7 September @ 21:00-24:00

**Comment by cesalazar** [comment]
Thanks for this PR. Two observations:
- There's an area for "More Information" that includes a "ticket:" key. Why not include the link to the RSVP in there, instead of the synopsis?
- Changing the slug/permalink just one week before the start of the events doesn't seem a good idea. But not up to me to decide, so if you insist, I'll merge as is.

> Oh one more thing, could we add another event/party to the website, like the Dezentral afterparty?

Sure. Either open a new issue for that topic and fill in the details, or create a new PR with the content.

**Comment by onurakpolat** [comment]
Thats great, thanks. To your points:

> There's an area for "More Information" that includes a "ticket:" key. Why not include the link to the RSVP in there, instead of the synopsis?

done.

> Changing the slug/permalink just one week before the start of the events doesn't seem a good idea. But not up to me to decide, so if you insist, I'll merge as is.

Yeah, fair point. We were planning to fill-up the event ourselves and have some additional traffic from your site as a bonus, so I'd say its okay if we loose a few due to that change.

> Sure. Either open a new issue for that topic and fill in the details, or create a new PR with the content.

Will create a PR.

**Comment by cesalazar** [comment]
Good. I'll merge now. Thanks!

**Pull request merged**
