### PR TITLE
added RCon3

### PR DESCRIPTION
**Pull request by 8lcarte**
Adding RChain Devcon3. The event shows up in the calendar but not on the events page? Is this happening because I'm out of the date range set up for the events page?

-Lee

### CODE REVIEW

**Comment by cesalazar** [comment]
Thanks for submitting this event!

I'm afraid I don't understand what do you mean.

> The event shows up in the calendar but not on the events page?
You mean the event shows on you local environment, after executing `npm run dev`? If so, then you probably can catch the error on the terminal or the dev console of the browser. At first glance seems like you're not following the instructions: the spacing is not as requested, which can cause problems when VuePress parses the file.

> Is this happening because I'm out of the date range set up for the events page?
Again, not sure what you mean. The events are from Sep. 5 to Sep. 11, both inclusive,  so this event is on the allowed range. With that said, does this event lasts 1 or 2 days? If 1 day, the **endDate** should be either empty or the same than **date**.

**Comment by 8lcarte** [comment]
Hey @cesalazar so i updated my formatting to follow the formatting instructions. When I run it on my local environment I still can't see the event on the events page. I can see it on the calendar page though. I'm not particularly adept at github, how do I request to add the updates I just made to the new fork you created?

**Comment by cesalazar** [comment]
No worries @8lcarte, I'll address the changes! Working on it now, should be live in a couple of minutes. Thanks for trying to address the corrections.

**Comment by 8lcarte** [comment]
Thank you! Love the community effort!

**Pull request merged**
